### PR TITLE
Set `after` to non null

### PR DESCRIPTION
**Pull request by bkchr**
@rzadp would be nice to get a release of this. On chain currently doesn't like `after = 0` :D

### CODE REVIEW

**Comment by rzadp** [comment]
@bkchr Does it have something to do with the `minEnactmentPeriod` value of a track?
If yes, we should set it to `25` because that's the value of `minEnactmentPeriod` on track `fellows`, right?

**Comment by bkchr** [comment]
Yeah it is related to the `minEnactmentPeriod`. With `25` this bug actually does not gets triggered and it is also already fixed. So yeah, the pr is actually not *that* useful :see_no_evil:

**Comment by rzadp** [comment]
> With `25` this bug actually does not gets triggered and it is also already fixed.

Do you mean that the chain actually likes `after = 0`, and just bumps it to `25`? So we can close the PR and continue to set `after` to `0`?

**Comment by bkchr** [comment]
Yeah let's close this! https://github.com/paritytech/polkadot-sdk/pull/4823 this was the bug.

**Pull request closed without merging**
